(defun lst_repeat (lst)
  (princ lst)
  (princ "\n")
  (setq resList '())
  (foreach i lst 
      (princ "\n")
      (setq a i)
      (princ a)
      (princ ":\n")
      (setq appear_times 0)
      (foreach j lst 
        (if (= j a) 
          (setq appear_times (+ 1 appear_times))
        )
      )
      (setq resList (append resList (list appear_times)))
      (princ appear_times)
  )
  (princ "\n Res List is ")
  (princ resList)
)
(lst_repeat '(1 2 34 "asf" 1 1 15 2 2 2))